export const projects = [
    {
        id: "esp32-weather",
        title: "🌦️ Station Météo IoT",
        desc: "Une station météo connectée et autonome conçue pour la surveillance environnementale en temps réel. Elle intègre la géolocalisation et la synchronisation horaire précise.",
        descShort: "Station météo IoT avec GPS, capteurs environnementaux et écran OLED.",
        long: "Ce projet repose sur un ESP32-S3 couplé à des capteurs de température et d'humidité (DHT). Il utilise un module GPS pour la géolocalisation et la synchronisation NTP pour une précision temporelle absolue. Les données sont affichées localement sur un écran OLED SSD1306 et peuvent être consultées via une interface web dédiée. Développé en C++ avec PlatformIO.",
        tags: ["IoT", "ESP32-S3", "C++", "GPS", "OLED"],
        demo: "https://canva.link/fcqwl3ulhqz81rs",
        repo: "https://github.com/Mastr00/wether",
        image: "/images/projects/esp32-wether.webp",
        created_at: "2025-10-24T11:31:46Z",
        idea: "Créer une station météorologique entièrement autonome capable de récolter des données environnementales précises géolocalisées, sans dépendre d'une connexion internet permanente.",
        challenges: "Le principal défi technique était de gérer la synchronisation entre les lectures capricieuses du capteur GPS (qui perd parfois le signal) et les lectures des capteurs I2C (écran OLED, DHT) sans bloquer la boucle principale du programme ESP32.",
        solution: "Mise en place d'une architecture asynchrone (FreeRTOS) sur l'ESP32 pour que chaque module (Acquisition GPS, Capteurs, Affichage, Web Server) tourne sur sa propre tâche avec des mutex de sécurité.",
        hardware: ["ESP32-S3", "Module GPS Neo-6M/8M", "Capteur Temp/Hum DHT22", "Écran OLED SSD1306 0.96\""]
    },
    {
        id: "trail-gps",
        title: "🧭 TrailNav GPS Companion",
        desc: "Compagnon GPS sur mesure basé sur ESP32-S3. Un appareil all-in-one offrant écran interactif, gestion SD, capteurs IMU (boussole/accéléromètre) et stockage persistant.",
        descShort: "Traceur GPS avec affichage TFT optimisé, boussole et module SD.",
        long: "Développé entièrement en C++ (PlatformIO), ce projet met en œuvre un traceur GPS portable sur un ESP32-S3 avec un écran 2.0\" TFT SPI. Il intègre une navigation d'interface fluide et sans scintillement grâce à TFT_eSprite, un stockage en NVS, la gestion des données GPS (Vitesse, Altitude, Signaux Satellites), et un lecteur SD dédié pour les tracés. L'architecture orientée objet assure robustesse et évolutivité matérielle.",
        tags: ["C++", "ESP32-S3", "GPS", "IoT", "Embedded"],
        demo: "https://canva.link/ejz8w3khle6447l",
        repo: "https://github.com/Mastr00/trail_GPS",
        image: "/images/projects/trail-gps.png",
        created_at: "2026-03-28T11:00:00Z",
        idea: "Développer une alternative open-source et personnalisable aux compteurs GPS commerciaux (type Edge) destinée au trail et au cyclisme, offrant un contrôle total sur ses données.",
        challenges: "Afficher une boussole et des jauges en temps réel sur l'écran TFT sans effets de scintillement (flickering), et gérer la perte occasionnelle du lecteur de carte SD en pleine utilisation à cause des vibrations.",
        solution: "Utilisation poussée de la librairie TFT_eSprite (buffer en RAM / double buffering) pour envoyer l'image calculée en un seul bloc SPI à l'écran. Développement d'un watchdog pour réinitialiser le bus SPI de la carte SD en cas d'erreur.",
        hardware: ["ESP32-S3", "Écran TFT 2.0\" SPI", "Lecteur Carte MicroSD", "Module GPS Intégré", "Capteur IMU 6-Axes (Boussole)"]
    },
    {
        id: "fall-guard",
        title: "🚨 Fall_guard",
        desc: "Système de sécurité intelligent pour personnes isolées. Ce dispositif détecte les chutes via l'analyse de mouvements et déclenche des alertes SOS géolocalisées.",
        descShort: "Détecteur de chute intelligent avec alertes SOS et suivi GPS.",
        long: "_guard utilise des données d'accéléromètre analysées par des algorithmes personnalisés pour distinguer les chutes réelles des mouvements normaux. Le système vérifie si la personne se relève (analyse post-chute) avant d'envoyer une alerte d'urgence contenant les coordonnées GPS précises aux contacts de sécurité. Conçu pour l'assistance aux personnes âgées ou aux explorateurs.",
        tags: ["Embedded", "C++", "Safety", "Accel", "GPS"],
        demo: "https://www.canva.com/design/DAGEGtVhnBw/0-vhrQnHjY428aMI4KPUaQ/view?utm_content=DAGEGtVhnBw&utm_campaign=designshare&utm_medium=link&utm_source=editor",
        repo: "https://github.com/Mastr00/Fall_guard",
        image: "/images/projects/fall-guard.png",
        created_at: "2024-05-28T11:13:43Z",
        idea: "Concevoir un petit module portable de sécurité vitale capable de détecter de manière fiable une chute brutale (personne âgée ou randonneur isolé) pour envoyer un signal au réseau.",
        challenges: "Le filtrage des faux positifs (trébuchement léger, s'asseoir brusquement) et la détection infaillible de la perte absolue d'équilibre suivi par une période d'immobilité.",
        solution: "Algorithme basé sur les seuils d'accélération différentielle : on guette un pic de 'Free Fall' suivi d'un impact soudain, couplé ensuite à un délai de 30 secondes d'immobilité. Si les trois conditions sont réunies, on déclenche l'alerte GPS.",
        hardware: ["Microcontrôleur Basse Consommation", "Accéléromètre MPU6050", "Module GSM/GPS (Connectivité)"]
    },
    {
        id: "ia-cam",
        title: "🤖 IA-Cam - Robot Suiveur",
        desc: "Robot suiveur capable de détecter et suivre un visage en temps réel grâce à l'IA. Combine vision par ordinateur et contrôle de servomoteurs pour un suivi fluide.",
        descShort: "Robot avec reconnaissance faciale et suivi automatique pan/tilt.",
        long: "Ce projet implémente un robot suiveur utilisant ESP32-CAM pour la capture vidéo, un serveur Python avec OpenCV pour la détection faciale, et un ESP32 séparé pour le contrôle des servomoteurs pan/tilt. L'architecture distribuée permet un traitement d'image performant tout en gardant un contrôle précis des mouvements de la caméra.",
        tags: ["ESP32-CAM", "Python", "OpenCV", "IoT", "Robotique"],
        demo: "https://canva.link/1nzeb6rmtnxb628",
        repo: "https://github.com/Mastr00/IA-Cam",
        image: "/images/projects/ia-cam.png",
        created_at: "2026-01-20T20:53:38Z",
        idea: "Mettre en pratique la vision par ordinateur en temps réel (machine learning) en l'intégrant au monde physique via une tourelle robotique Pan/Tilt qui suit ma tête.",
        challenges: "L'ESP32-CAM manquait de puissance brute pour faire tourner un modèle OpenCV complexe à haut framerate sans surchauffer ou figer le stream vidéo.",
        solution: "Délégation du calcul ! L'ESP-CAM ne fait plus qu'envoyer le flux vidéo brut (MJPEG) vers un script Python sur PC. Le script fait la détection OpenCV et envoie seulement de petits paquets via WebSocket (ex: 'X+2, Y-1') à l'ESP pour ajuster les servomoteurs.",
        hardware: ["ESP32-CAM (Caméra OV2640)", "Servomoteurs SG90 (Axe Pan & Tilt)", "Support Robotique Imprimé 3D"]
    },
    {
        id: "portfolio-v2",
        title: "✨ Mon Portfolio V2",
        desc: "Ce site personnel ! Une vitrine interactive de mes compétences et projets, alliant design moderne et performance technique.",
        descShort: "Portfolio interactif : Next.js, Framer Motion et Glassmorphism.",
        long: "Développé avec Next.js 14 et TailwindCSS, ce portfolio adopte un design 'Glassmorphism' avec des animations fluides gérées par Framer Motion. Il est entièrement Responsive, optimisé pour le SEO et n'utilise désormais plus de base de données (architecture 100% statique) pour une vitesse de chargement maximale.",
        tags: ["Next.js", "React", "Design", "TailwindCSS"],
        demo: "https://mmsa.app/",
        repo: "https://github.com/Mastr00/mon-site-perso",
        image: "/images/projects/portfolio.jpg",
        created_at: "2025-09-24T21:39:13Z",
        idea: "Refondre mon portfolio statique pour refléter véritablement mes compétences actuelles, en intégrant des animations next-gen, un support multilingue et un CMS statique.",
        challenges: "Gérer un système de mode Clair / Sombre complexe (car le design d'origine \"Neon/Hacker\" est prévu pour être sombre) tout en gardant le style lisible sur fond clair.",
        solution: "Exploitation profonde et complète des classes `dark:` de Tailwind avec des abstractions de couleurs pour un basculement de thème parfait. Le routing dynamique de Next.js permet de générer des pages par projet sans effort base de données.",
        hardware: ["(Logiciel) Next.js 14", "TailwindCSS + Framer Motion", "Vercel Hosting"]
    },
    {
        id: "lidar-radar",
        title: "📡 Lidar Radar System",
        desc: "Un système de cartographie et de télémétrie 3D haute performance. Il exploite la technologie Time-of-Flight (ToF) pour visualiser l'environnement spatial.",
        descShort: "Cartographie et ranging 3D via capteur Lidar et interface Web.",
        long: "Basé sur l'ESP32-S3 et le capteur VL53L5CX, ce projet permet la capture de données de distance en 3D. Il intègre un serveur web asynchrone (ESPAsyncWebServer) pour visualiser les données (mapping) en temps réel sur une interface navigateur. Optimisé pour utiliser la PSRAM de l'ESP32 pour le traitement rapide des matrices de distance.",
        tags: ["Lidar", "3D Mapping", "ESP32", "C++", "Web Interface"],
        demo: "#",
        repo: "https://github.com/Mastr00/lidar_radar",
        image: "/images/projects/lidar.jpg",
        created_at: "2025-11-12T17:21:53Z",
        idea: "Transformer un simple capteur ToF multi-zones en un véritable scanner 3D / Radar embarqué qui transmet la cartographie spatiale sans délai (temps réel) vers le web.",
        challenges: "Traiter la montagne de données générée à 15 Hz par la matrice 8x8 du capteur Lidar (soit des milliers de pixels de distance convertis à la seconde) et l'envoyer par Wi-Fi sans bégaiement côté navigateur.",
        solution: "Activation et utilisation de la PSRAM (RAM externe) de l'ESP32-S3 pour accumuler le buffer de la matrice. Envoi structuré en JSON via Server-Sent Events (SSE) asynchrone pour que le front-end reçoive la frame fluide et dessine la heatmap.",
        hardware: ["ESP32-S3 avec PSRAM", "Capteur Lidar multi-zones ToF (VL53L5CX)"]
    }
];
